### ISSUE TITLE
Running CCT with python3 

### ISSUE THREAD

**Issue by RogerStu** [IBM/websphere-cct#28]
We converted the python scripts to version 3 using 2to3 . -w and now we get:
Traceback (most recent call last):                                                          
  File "/shared/wasconfig/scripts/cct/ConfigReport.py", line 1776, in <module>              
    NodeAgentReport()            #Ref0012                                                   
  File "/shared/wasconfig/scripts/cct/ConfigReport.py", line 1068, in NodeAgentReport       
    subReport[1](serverList)                                                                
  File "/shared/wasconfig/scripts/cct/ConfigReport.py", line 692, in pmiServiceReportSrv    
    reportPMIStatProviders(rptParms)                                                        
  File "/shared/wasconfig/scripts/cct/ConfigReport.py", line 383, in reportPMIStatProviders 
    row.append(cu.getPMICellValue(cu.getPMIConfig(name,server)))                            
  File "/shared/wasconfig/scripts/cct/ConfigUtils.py", line 903, in getPMICellValue         
    intVals.append(int(val))                                                                
ValueError: invalid literal for int() with base 10: '*'                                     

Any ideas on this?
regards Roger

**Comment by scottkurz** [comment]
Jython 2.7 only supports Python 2.  Though there seem to be efforts https://github.com/jython/jython to develop a Python 3 compatible version of Jython, there are not to my knowledge any plans to update wsadmin to support such a new version of Jython.

I think we can just close this and say users have to stay with Python 2 then.

**Comment by scottkurz** [comment]
On second thought, perhaps this is better to leave open.  It's more visible if anyone looks to see if there's an issue open already.  To my knowledge, there's no reason to shut the door on the idea and discourage anyone to pursue this if they are motivated.

**Comment by riddlemo** [comment]
Unless ConfigDump.py and ConfigReport.py no longer share any Python code, it will not be possible to run CCT in Python 3.  WAS Jython is Python 2.7 based.  This is a large effort and I do not expect to be able to handle it any time soon.  It also sets up dual maintenance issues making future support of CCT more complicated.  I prefer to keep CCT on Python 2.7.

**Comment by kgibm** [comment]
I'm not sure why, but I was able to run this on an 8.5.5.23 comparison (I couldn't find or install Python2 where the data was available). I ran `2to3`, removed all `True=1` and `False=0` lines and then it worked and the output is as expected:

```
$ python3 ConfigReport.py ConfigurationDumpFiles=DmgrCell-23-11-17-16-26-37.cfg,DmgrCell-23-11-17-16-34-05.cfg
[...]
[23/11/20 20:11:32] End run.
```

**Comment by riddlemo** [comment]
That is great news!  I thought Python 3 did not support the same syntax.  All I have to do, then, is figure out if Python 2 or 3 is in use and only set those if the former.  I'll look into that.


Regards,

Dennis Riddlemoser, Senior Technical Account Manager
IBM Expertise Connect

IBM Expert Labs
Phone: (720) 342-5689
Email: ***@***.******@***.***>



________________________________
From: Kevin Grigorenko ***@***.***>
Sent: Monday, November 20, 2023 3:26 PM
To: IBM/websphere-cct ***@***.***>
Cc: Dennis Riddlemoser ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [IBM/websphere-cct] Running CCT with python3 (Issue #28)

I'm not sure why, but I was able to run this on an 8. 5. 5. 23 comparison (I couldn't find or install Python2 where the data was available). I ran 2to3, removed all True=1 and False=0 lines and then it worked and the output is as expected: $ python3
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
<https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2Y-u7PHcolMw8k2w0ikPLUJ-izWCTtSwvMtbcbt3ZuMVmtzY9FyPUcMgEOI5bzd9GTOZY10kzvomGjYTvRJhMncwKE5TS8MTJ0Q6$>
Report Suspicious

ZjQcmQRYFpfptBannerEnd

I'm not sure why, but I was able to run this on an 8.5.5.23 comparison (I couldn't find or install Python2 where the data was available). I ran 2to3, removed all True=1 and False=0 lines and then it worked and the output is as expected:

$ python3 ConfigReport.py ConfigurationDumpFiles=DmgrCell-23-11-17-16-26-37.cfg,DmgrCell-23-11-17-16-34-05.cfg
[...]
[23/11/20 20:11:32] End run.

**Comment by ZmanNorthern** [comment]
Interesting [kgibm](https://github.com/kgibm)! 

I am having the opposit issues, I also did the 2to3 on the following .py files and that seems to have fixed the issue with run on my WAS 9.0.5.25 environment but I cant run it on my 8.5.5.XX environment. Getting syntax errors. 


files i did the 2to3 on:
          python -m lib2to3 -w ConfigDump.py
           python -m lib2to3 -w ConfigReport.py
           python -m lib2to3 -w ConfigUtils.py
           python -m lib2to3 -w ConfigCompare.py
           python -m lib2to3 -w WAuJ_utilities.py

Ran the following for WAS9:
D:\wcct>D:\wasprofile\AppSrv9\bin\wsadmin.bat -lang jython -conntype NONE -f D:\wcct\ConfigDump.py

This actually pulls the .cfg with no issues. 

Ran the following for WAS8:
D:\wcct>D:\wasprofile\AppSrv\bin\wsadmin.bat -lang jython -conntype NONE -f D:\wcct\ConfigDump.py

and get the error: 

D:\wcct>D:\wasprofile\AppSrv\bin\wsadmin.bat -lang jython -conntype NONE -f ConfigDump.py WASX7357I: By request, this scripting client is not connected to any server process. Certain configuration and application operations will be available in local mode. Failed to get environment, environ will be empty: (0, 'Failed to execute command ([\'sh\', \'-c\', \'env\']): java.io.IOException: Cannot run program "sh": CreateProcess error=2, The system cannot find the file specified') ERROR: Failed to load support scripts. exceptions.NameError False <traceback object at 740593665> ERROR, cannot continue. Failed to load support scripts. Run wsadmin -f ConfigDump.py from the same directory it exists in.

ConfigDump.py is located in D:\wcct>

Any thoughts or comments would be most helpful!
