### ISSUE TITLE
Unable to run the config report for multiple cells.

### ISSUE THREAD

**Issue by vadimh001** [IBM/websphere-cct#34]
Hello,
We are getting this error when trying to run the config report .

Please help.

[24/03/12 18:46:41] Running ORB
[24/03/12 18:46:41] Running PMI
Traceback (most recent call last):
  File "/opt/app/EAS/cct/tool/ConfigReport.py", line 1775, in <module>
    NodeAgentReport()            #Ref0012
  File "/opt/app/EAS/cct/tool/ConfigReport.py", line 1067, in NodeAgentReport
    subReport[1](serverList)
  File "/opt/app/EAS/cct/tool/ConfigReport.py", line 691, in pmiServiceReportSrv
    reportPMIStatProviders(rptParms)
  File "/opt/app/EAS/cct/tool/ConfigReport.py", line 382, in reportPMIStatProviders
    row.append(cu.getPMICellValue(cu.getPMIConfig(name,server)))
  File "/opt/app/EAS/cct/tool/ConfigUtils.py", line 903, in getPMICellValue
    intVals.append(int(val))
ValueError: invalid literal for int() with base 10: '*'

**Comment by vadimh001** [comment]
We are using Python 2.7

**Comment by vadimh001** [comment]
It seems that our issue is related to PMI module.  I see that we have PMI is set to "Custom" in WAS config and these are causing this last error.  How do we bypass PMI?
